### ISSUE TITLE
Syntax choice

### ISSUE THREAD

**Issue by iluuu1994** [uuf6429/expression-language-arrowfunc#3]
Cool project! Just found it by coincidence. 🤘

Is there a particular reason you chose to use `->` instead of `=>` for the arrow (e.g. ambiguity)?  
Most popular languages use the `=>` operator (JavaScript, C#). There's also an [RFC](https://wiki.php.net/rfc/arrow_functions) for PHP that also suggests using the `=>` operator.

Additionally, single parameters are often not required to be wrapped in parenthesis. 

Are you planning on creating a pull request for the official Symfony repo? If so, I think this would be the most intuitive syntax for most users.

**Comment by uuf6429** [comment]
Hi there!
- Initially I decide to use `->` because it's more natural outside programming circles (eg; quite popular in mathematics and physics)
- That said, I have a ticket to add the ability to change the operator (see issue #2).
- I had already created [a PR in Symfony](https://github.com/symfony/symfony/pull/19956) but it didn't get the go-ahead, so I closed it

**Comment by iluuu1994** [comment]
@uuf6429 Added my two cents to the PR. I don't think it's gonna change anything but at least I tried 😉
Unfortunate, not sure how they can't see the huge potential in adding this feature.

**Comment by uuf6429** [comment]
Thanks for the feedback!
